const { format } = require('date-fns');
const a = [
  {
    uid: 'dpl_Gq4UnRcYq6v7t58kp4MfEwi2ivMv',
    name: 'repository-time',
    url: 'repository-time-56319x2y1-bellaalimm23s-projects.vercel.app',
    created: 1719294932780,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/Gq4UnRcYq6v7t58kp4MfEwi2ivMv',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan halaman admin mahasiswa',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '097cefd8241629a562e3a7b9c4e9d1c7329200cb',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1719295034354,
    isRollbackCandidate: true,
    createdAt: 1719294932780,
    buildingAt: 1719294933979,
    ready: 1719295033813,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_HVndGPnLjg1eTeNu5fVgS3qkbqJo',
    name: 'repository-time',
    url: 'repository-time-gml9y7ef3-bellaalimm23s-projects.vercel.app',
    created: 1719152154915,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/HVndGPnLjg1eTeNu5fVgS3qkbqJo',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'ubah struktur folder',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'b2fa7ae5b911859573f145934872afcdcba2f4e5',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1719152272506,
    isRollbackCandidate: true,
    createdAt: 1719152154915,
    buildingAt: 1719152156216,
    ready: 1719152272006,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_A2A367BzNDeZzMwGC15RZDB6QNsL',
    name: 'repository-time',
    url: 'repository-time-9a4jmzumz-bellaalimm23s-projects.vercel.app',
    created: 1719115920449,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/A2A367BzNDeZzMwGC15RZDB6QNsL',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan api',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '22ff973873339fa657ddb93b7963e1ae383cc7b3',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1719116027269,
    isRollbackCandidate: false,
    createdAt: 1719115920449,
    buildingAt: 1719115921579,
    ready: 1719116026797,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_8p87kMgUvy84wmRL9UXTzLxBJ8mp',
    name: 'repository-time',
    url: 'repository-time-orvzwp63g-bellaalimm23s-projects.vercel.app',
    created: 1719026505470,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/8p87kMgUvy84wmRL9UXTzLxBJ8mp',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan data me',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '9480b45c43e6f9987b0fcf2378365cc8236f2503',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1719026604594,
    isRollbackCandidate: false,
    createdAt: 1719026505470,
    buildingAt: 1719026506742,
    ready: 1719026604065,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_AMrzgQu3TfX2MxqHcyZoewZHX6y7',
    name: 'repository-time',
    url: 'repository-time-6n99osc6v-bellaalimm23s-projects.vercel.app',
    created: 1718966699389,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/AMrzgQu3TfX2MxqHcyZoewZHX6y7',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan tampilan mahasiswa',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'd3f7cdfcb8f7a9c53dbd270f7aa76fdb5f9d8040',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718966810990,
    isRollbackCandidate: false,
    createdAt: 1718966699389,
    buildingAt: 1718966700893,
    ready: 1718966810606,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_9YrNQ76W2VfJtaZuvN588NbFP2rw',
    name: 'repository-time',
    url: 'repository-time-cypgn08t0-bellaalimm23s-projects.vercel.app',
    created: 1718966237119,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/9YrNQ76W2VfJtaZuvN588NbFP2rw',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan pembaharuan data',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '4f3cec5d65eeb97f921908fe12e34907275edcb1',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718966340183,
    isRollbackCandidate: false,
    createdAt: 1718966237119,
    buildingAt: 1718966238567,
    ready: 1718966339846,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_9MT9AoUntzoRrcXMzu9KR5dmAikH',
    name: 'repository-time',
    url: 'repository-time-meoe9f63z-bellaalimm23s-projects.vercel.app',
    created: 1718966058677,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/9MT9AoUntzoRrcXMzu9KR5dmAikH',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan tampilan profil',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '241f9c2acbf7e919fa02a9fb15a2395453825731',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718966167081,
    isRollbackCandidate: false,
    createdAt: 1718966058677,
    buildingAt: 1718966059892,
    ready: 1718966166703,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_HSRC37u1CiwLkJjcgS3Q8yNjY8Uz',
    name: 'repository-time',
    url: 'repository-time-qkdvcb52f-bellaalimm23s-projects.vercel.app',
    created: 1718964248227,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/HSRC37u1CiwLkJjcgS3Q8yNjY8Uz',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan hapus data',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '444422e94f916e090c50cfaabfb08cd6632ce390',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718964378743,
    isRollbackCandidate: false,
    createdAt: 1718964248227,
    buildingAt: 1718964250580,
    ready: 1718964378007,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_9jfT7x6t59ox8dcqMtgZkj2XmLRA',
    name: 'repository-time',
    url: 'repository-time-ayjcmy4c1-bellaalimm23s-projects.vercel.app',
    created: 1718959187807,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/9jfT7x6t59ox8dcqMtgZkj2XmLRA',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'integrasi hapus data',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '3ce84eec4063ddf94a859f72c94565106c032e32',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718959309861,
    isRollbackCandidate: false,
    createdAt: 1718959187807,
    buildingAt: 1718959189147,
    ready: 1718959309432,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_JA9oFjL2RcUr9yjFjpmot4mHaKPv',
    name: 'repository-time',
    url: 'repository-time-iin88ea7t-bellaalimm23s-projects.vercel.app',
    created: 1718955095419,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/JA9oFjL2RcUr9yjFjpmot4mHaKPv',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'perbaikan header dan navigasi',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'bf7ce7a48d5fa23b512e42d1a75bf6b029d20ba3',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718955219166,
    isRollbackCandidate: false,
    createdAt: 1718955095419,
    buildingAt: 1718955098927,
    ready: 1718955218074,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_B3UWFEkyJLE11RRrMU8LaBdJ4urN',
    name: 'repository-time',
    url: 'repository-time-pis8cy5ta-bellaalimm23s-projects.vercel.app',
    created: 1718954726648,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'STAGED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/B3UWFEkyJLE11RRrMU8LaBdJ4urN',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'integrasi supabase file',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'revise/major-01',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '9a61b090c4b6daba8408c44b58753f045955ee11',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias:
        'repository-time-git-revise-major-01-bellaalimm23s-projects.vercel.app',
    },
    target: null,
    aliasError: null,
    aliasAssigned: 1718954914767,
    isRollbackCandidate: false,
    createdAt: 1718954726648,
    buildingAt: 1718954766822,
    ready: 1718954914434,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_6Aky2u5PJJdojDtLRdtDLyLG6G1C',
    name: 'repository-time',
    url: 'repository-time-gia892gru-bellaalimm23s-projects.vercel.app',
    created: 1718954612621,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/6Aky2u5PJJdojDtLRdtDLyLG6G1C',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage:
        "Merge commit '9a61b090c4b6daba8408c44b58753f045955ee11'",
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'c04b28b84e73bd24a73ee27607816c8331cecebf',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718954766064,
    isRollbackCandidate: false,
    createdAt: 1718954612621,
    buildingAt: 1718954616279,
    ready: 1718954765181,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_BJdND6YijH2NfWVnw5A9DSivfTEu',
    name: 'repository-time',
    url: 'repository-time-htdcn3uj9-bellaalimm23s-projects.vercel.app',
    created: 1718951957751,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
      githubLogin: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/BJdND6YijH2NfWVnw5A9DSivfTEu',
    meta: {
      githubCommitAuthorName: 'bellalimm23',
      githubCommitMessage:
        'Merge pull request #1 from bellalimm23/revise/major-01\n\nintegrasi database',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'fac8dd9873c471271de835ff2f5444d7375ebcda',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      githubCommitAuthorLogin: 'bellalimm23',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1718952089897,
    isRollbackCandidate: false,
    createdAt: 1718951957751,
    buildingAt: 1718951960739,
    ready: 1718952089537,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_J6fRcc4c7yQitkJGta5WnCEJPw69',
    name: 'repository-time',
    url: 'repository-time-jfhyn24r6-bellaalimm23s-projects.vercel.app',
    created: 1714315237476,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'STAGED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/J6fRcc4c7yQitkJGta5WnCEJPw69',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'evaluasi register dan login',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'revise/major-01',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '799a6cada2ef4bdbbaa7da036f5f0ece6caa774f',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      branchAlias:
        'repository-time-git-revise-major-01-bellaalimm23s-projects.vercel.app',
    },
    target: null,
    aliasError: null,
    aliasAssigned: 1714315350215,
    isRollbackCandidate: false,
    createdAt: 1714315237476,
    buildingAt: 1714315238641,
    ready: 1714315350101,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_A3mSAukNxRgUzhVWSjo19hvwHGP1',
    name: 'repository-time',
    url: 'repository-time-mp2wwzxxx-bellaalimm23s-projects.vercel.app',
    created: 1713073599727,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/A3mSAukNxRgUzhVWSjo19hvwHGP1',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'evaluasi admin user (tambah foto profil)',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '13c4e1ee6b24629786a096ce3abc5fde8aae33ae',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'private',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1713073672490,
    isRollbackCandidate: false,
    createdAt: 1713073599727,
    buildingAt: 1713073600913,
    ready: 1713073672069,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_14ULZRfM22aBZ794uPTcV1GpuhFd',
    name: 'repository-time',
    url: 'repository-time-csc0ka3jx-bellaalimm23s-projects.vercel.app',
    created: 1713072771218,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/14ULZRfM22aBZ794uPTcV1GpuhFd',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'evaluasi menu profil (tambah foto profil)',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '387783ae40dc465f1b1dc90f554ebc1a65852eb1',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'private',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1713072875891,
    isRollbackCandidate: false,
    createdAt: 1713072771218,
    buildingAt: 1713072772428,
    ready: 1713072875442,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_BnoGzrF6daNt2Q6s7zPqjjH1KggC',
    name: 'repository-time',
    url: 'repository-time-l5kqtpyw0-bellaalimm23s-projects.vercel.app',
    created: 1708799821348,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
      githubLogin: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/BnoGzrF6daNt2Q6s7zPqjjH1KggC',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'evaluasi fitur profil',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'b73c7614133cf9b45a0531dfef5c452b075db385',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      githubCommitAuthorLogin: 'bellalimm23',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1708799903063,
    isRollbackCandidate: false,
    createdAt: 1708799821348,
    buildingAt: 1708799822156,
    ready: 1708799902621,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_2Lpoo3zE9muatbyJHT2Lei6hix3Y',
    name: 'repository-time',
    url: 'repository-time-gllsbv6xw-bellaalimm23s-projects.vercel.app',
    created: 1708797587298,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
      githubLogin: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/2Lpoo3zE9muatbyJHT2Lei6hix3Y',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'evaluasi fitur tugas akhir',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: '581e3e7afb4271f9de3d449c54625cc9e8fae218',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      githubCommitAuthorLogin: 'bellalimm23',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1708797679444,
    isRollbackCandidate: false,
    createdAt: 1708797587298,
    buildingAt: 1708797588081,
    ready: 1708797678984,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_DRxGAYfM1bniW7Z3jmmfnEa8zFzk',
    name: 'repository-time',
    url: 'repository-time-g1nlzu6pv-bellaalimm23s-projects.vercel.app',
    created: 1708614894496,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
      githubLogin: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/DRxGAYfM1bniW7Z3jmmfnEa8zFzk',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage:
        'tambah fitur daftar user, daftar thesis, detail user, detail thesis',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'e6c128126c26ffa0f9022a282c003aac5d78bba7',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      githubCommitAuthorLogin: 'bellalimm23',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1708614985401,
    isRollbackCandidate: false,
    createdAt: 1708614894496,
    buildingAt: 1708614896017,
    ready: 1708614984983,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
  {
    uid: 'dpl_7n2mBgJRZZ2hZvyPS5tQ874kPHK8',
    name: 'repository-time',
    url: 'repository-time-3ur7hszs9-bellaalimm23s-projects.vercel.app',
    created: 1708185948478,
    source: 'git',
    state: 'READY',
    readyState: 'READY',
    readySubstate: 'PROMOTED',
    type: 'LAMBDAS',
    creator: {
      uid: 'HH82EA3YCndSguS4AObXPIKu',
      email: 'bellaalimm23@gmail.com',
      username: 'bellalimm23',
      githubLogin: 'bellalimm23',
    },
    inspectorUrl:
      'https://vercel.com/bellaalimm23s-projects/repository-time/7n2mBgJRZZ2hZvyPS5tQ874kPHK8',
    meta: {
      githubCommitAuthorName: 'bellaalimm23',
      githubCommitMessage: 'fix phospor',
      githubCommitOrg: 'bellalimm23',
      githubCommitRef: 'main',
      githubCommitRepo: 'repository-time',
      githubCommitSha: 'b8b2ea9a3b21e1e48fc9e3e42286e91e6522f4de',
      githubDeployment: '1',
      githubOrg: 'bellalimm23',
      githubRepo: 'repository-time',
      githubRepoOwnerType: 'User',
      githubCommitRepoId: '754421751',
      githubRepoId: '754421751',
      githubRepoVisibility: 'public',
      githubCommitAuthorLogin: 'bellalimm23',
      branchAlias: 'repository-time-git-main-bellaalimm23s-projects.vercel.app',
    },
    target: 'production',
    aliasError: null,
    aliasAssigned: 1708186055698,
    isRollbackCandidate: false,
    createdAt: 1708185948478,
    buildingAt: 1708185949251,
    ready: 1708186055315,
    projectSettings: {
      commandForIgnoringBuildStep: null,
    },
  },
].map((item) => {
  return {
    Url: item.url,
    Created: format(new Date(item.createdAt), 'dd MMM yyyy, HH:mm'),
    'Commit Message': item.meta.githubCommitMessage,
    Ready: format(new Date(item.ready), 'dd MMM yyyy, HH:mm'),
  };
});

const data = [
  {
    Url: 'repository-time-56319x2y1-bellaalimm23s-projects.vercel.app',
    Created: '25 Jun 2024, 12:55',
    'Commit Message': 'perbaikan halaman admin mahasiswa',
    Ready: '25 Jun 2024, 12:57',
  },
  {
    Url: 'repository-time-gml9y7ef3-bellaalimm23s-projects.vercel.app',
    Created: '23 Jun 2024, 21:15',
    'Commit Message': 'ubah struktur folder',
    Ready: '23 Jun 2024, 21:17',
  },
  {
    Url: 'repository-time-9a4jmzumz-bellaalimm23s-projects.vercel.app',
    Created: '23 Jun 2024, 11:12',
    'Commit Message': 'perbaikan api',
    Ready: '23 Jun 2024, 11:13',
  },
  {
    Url: 'repository-time-orvzwp63g-bellaalimm23s-projects.vercel.app',
    Created: '22 Jun 2024, 10:21',
    'Commit Message': 'perbaikan data me',
    Ready: '22 Jun 2024, 10:23',
  },
  {
    Url: 'repository-time-6n99osc6v-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 17:44',
    'Commit Message': 'perbaikan tampilan mahasiswa',
    Ready: '21 Jun 2024, 17:46',
  },
  {
    Url: 'repository-time-cypgn08t0-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 17:37',
    'Commit Message': 'perbaikan pembaharuan data',
    Ready: '21 Jun 2024, 17:38',
  },
  {
    Url: 'repository-time-meoe9f63z-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 17:34',
    'Commit Message': 'perbaikan tampilan profil',
    Ready: '21 Jun 2024, 17:36',
  },
  {
    Url: 'repository-time-qkdvcb52f-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 17:04',
    'Commit Message': 'perbaikan hapus data',
    Ready: '21 Jun 2024, 17:06',
  },
  {
    Url: 'repository-time-ayjcmy4c1-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 15:39',
    'Commit Message': 'integrasi hapus data',
    Ready: '21 Jun 2024, 15:41',
  },
  {
    Url: 'repository-time-iin88ea7t-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 14:31',
    'Commit Message': 'perbaikan header dan navigasi',
    Ready: '21 Jun 2024, 14:33',
  },
  {
    Url: 'repository-time-pis8cy5ta-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 14:25',
    'Commit Message': 'integrasi supabase file',
    Ready: '21 Jun 2024, 14:28',
  },
  {
    Url: 'repository-time-gia892gru-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 14:23',
    'Commit Message': "Merge commit '9a61b090c4b6daba8408c44b58753f045955ee11'",
    Ready: '21 Jun 2024, 14:26',
  },
  {
    Url: 'repository-time-htdcn3uj9-bellaalimm23s-projects.vercel.app',
    Created: '21 Jun 2024, 13:39',
    'Commit Message':
      'Merge pull request #1 from bellalimm23/revise/major-01\n' +
      '\n' +
      'integrasi database',
    Ready: '21 Jun 2024, 13:41',
  },
  {
    Url: 'repository-time-jfhyn24r6-bellaalimm23s-projects.vercel.app',
    Created: '28 Apr 2024, 21:40',
    'Commit Message': 'evaluasi register dan login',
    Ready: '28 Apr 2024, 21:42',
  },
  {
    Url: 'repository-time-mp2wwzxxx-bellaalimm23s-projects.vercel.app',
    Created: '14 Apr 2024, 12:46',
    'Commit Message': 'evaluasi admin user (tambah foto profil)',
    Ready: '14 Apr 2024, 12:47',
  },
  {
    Url: 'repository-time-csc0ka3jx-bellaalimm23s-projects.vercel.app',
    Created: '14 Apr 2024, 12:32',
    'Commit Message': 'evaluasi menu profil (tambah foto profil)',
    Ready: '14 Apr 2024, 12:34',
  },
  {
    Url: 'repository-time-l5kqtpyw0-bellaalimm23s-projects.vercel.app',
    Created: '25 Feb 2024, 01:37',
    'Commit Message': 'evaluasi fitur profil',
    Ready: '25 Feb 2024, 01:38',
  },
  {
    Url: 'repository-time-gllsbv6xw-bellaalimm23s-projects.vercel.app',
    Created: '25 Feb 2024, 00:59',
    'Commit Message': 'evaluasi fitur tugas akhir',
    Ready: '25 Feb 2024, 01:01',
  },
  {
    Url: 'repository-time-g1nlzu6pv-bellaalimm23s-projects.vercel.app',
    Created: '22 Feb 2024, 22:14',
    'Commit Message':
      'tambah fitur daftar user, daftar thesis, detail user, detail thesis',
    Ready: '22 Feb 2024, 22:16',
  },
  {
    Url: 'repository-time-3ur7hszs9-bellaalimm23s-projects.vercel.app',
    Created: '17 Feb 2024, 23:05',
    'Commit Message': 'fix phospor',
    Ready: '17 Feb 2024, 23:07',
  },
];

// Function to convert data to CSV
function convertToCSV(data) {
  const csvRows = [];

  // Get headers from the first object's keys
  const headers = Object.keys(data[0]);
  csvRows.push(headers.join(','));

  // Loop through data and add rows to CSV
  for (const item of data) {
    const values = headers.map((header) => item[header]);
    csvRows.push(values.join(','));
  }

  return csvRows.join('\n');
}

// Generate CSV string
const csvContent = convertToCSV(data);

// Create a Blob object with the CSV content
const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });

// Create a link element to trigger download
const link = document.createElement('a');
link.href = URL.createObjectURL(blob);
link.download = 'data.csv';
link.click();

// Revoke the object URL to avoid memory leaks
URL.revokeObjectURL(link.href);
